---
# tasks file for package_dependencies

- name: Installting dependencies
  yum:
    name='{{ item }}'
    state=installed
  with_items:
      - epel-release
      - python
      - python-setuptools
      - python-devel
      - python-pip

